<a href="https://colab.research.google.com/github/kei01138/3minuteDeeplearning/blob/master/1_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D_%ED%95%B4%EB%B3%B4%EC%9E%90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 텐서플로우 프로그래밍 해보자

텐서플로우는 딥러닝 프레임워크로 유명하지만, 사실 딥러닝용으로만 사용할 수 있는 것은 아닙니다.   
그래프 형태의 수학적 계산을 수행하는 핵심 라이브러리를 구현한 후,   
그 위에 딥러닝을 포함한 여러 머신러닝을 쉽게 할 수 있는 다양한 라이브러리를 올린 형태입니다.  

이를 위해 텐서플로우는 일반적인 프로그래밍 방식과는 약간 다른 개념들을 포함합니다.   
이러한 텐서플로우를 사용하는 데 필요한 **텐서(Tensor)**, **플레이스홀더(Placeholder)**, **변수(Variable)**   
그리고 **연산**의 개념과 **그래프**를 실행하는 기본적인 방법을 배워봅니다 

## 텐서와 그래프 실행

새로운 프로그래밍 언어나 라이브러리를 학습하는 가장 좋은 방법은 직접 코드를 입력해가며 배우는 것이 가장 쉽고 재미있는 방법입니다.

하나씩 공부해봅시다

먼저 텐서플로를 사용하기 위해 라이브러리를 가져옵시다





In [0]:
import tensorflow as tf

다음은 **tf.constant** 상수를 **hello** 변수에 저장합시다.  
텐서플로의 상수는 일반 프로그래밍 언어에서 써온 상수와 같다고 보면 됩니다

In [58]:
hello = tf.constant('Hello, Tensorflow!')
print(hello)

Tensor("Const_12:0", shape=(), dtype=string)


여기까지 입력하고 소스코드를 실행하면 다음 결과를 보실 수 있습니다.


```shell
Tensor("Const:0", shape=(), dtype=string)
```

**hello** 변수의 값을 출력한 결과로,  
hello가 텐서플로의 **텐서(Tensor)** 라는 자료형이고,  
상수를 담고 있음을 의미합니다.  

텐서는 텐서플로에서 다양한 수학식을 계싼하기 위해 가장 기본적이고 중요한 자료형이며,  
다음과 같이 **랭크(Rank)** 와 **셰이프(Shape)** 라는 개념을 가지고 있습니다.


In [59]:
3 # 랭크가 0인 텐서; 셰이프는 []
[1.,2.,3.] # 랭크가 1인 텐서; 셰이프는 [3]
[[1.,2.,3.], [4.,5.,6.]] # 랭크가 2인 텐서; 셰이프는 [2,3]
[[[1.,2.,3.]], [[7.,8.,9.]]] # 랭크가 3인 텐서; 셰이프는 [2,1,3]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

텐서 자료형의 형태는 배열과 비슷하다고 생각하면 됩니다.  
보는 바와 같이 랭크는 차원의 수를 나타내는 것으로써,  
랭크가 0이면 스칼라, 1이면 벡터, 2면 행렬, 3 이상이면 n-Tensor 또는 n차원 텐서라고 부릅니다.  
그리고 셰이프는 각 차원의 요소 개수로, 텐서의 구조를 설명해줍니다.  
텐서를 출력할 때 나오는 dtype은 해당 텐서에 담긴 요소들의 자료형입니다.  
string, float, int 등이 올 수 있습니다.



이러한 텐서를 이용해 다양한 **연산**을 수행할 수 있으며, 덧셈은 다음처럼 간단히 할 수 있습니다.

In [60]:
# 그래프 생성
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)
print(c)

Tensor("Add_11:0", shape=(), dtype=int32)


일반적인 프로그래머라면 이 코드를 실행하면 42가 나올 것으로 생각할 수 있습니다.  
하지만 다음과 같이 텐서의 형태를 출력합니다.  



```shell
Tensor("Add:0", shape=(), dtype=int32)
```



그 이유는 텐서플로 프로그램의 구조가 다음의 두가지로 분리되어 있기 때문입니다.

> 1.그래프 생성  -> tf.constant 사용 했던 부분  
> 2.그래프 실행  -> sess.run(c), 연산을 실제로 수행

**그래프**는 간단하게 말해 텐서들의 연산 모음이라고 생각합니다.  
텐서플로우는 텐서와 텐서의 연산들을 먼저 정의해 그래프를 만들고,  
이후 필요할 때 연산을 실행하는 코드를 넣어 **원하는 시점**에 실제 연산을 수행하도록 합니다.  
참고로 이러한 방식을 **지연 실행**이라고 하며, 함수형 프로그래밍에서 많이 사용합니다.  

그래프의 실행은 Session 안에서 이뤄져야 하며,  
다음과 같이 Session 객체와 run 메서드를 이용하면 됩니다


In [61]:
# 그래프 실행
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

Hello, Tensorflow!
[10, 32, 42]


이제 코드를 실행하면 다음과 같이 기대한 계산 결과를 볼 수 있습니다.  


```
Hello, Tensorflow!
[10, 32, 42]
```

아래는 전체 코드입니다



```python
# 텐서플로우의 기본적인 구성을 익힙니다.
import tensorflow as tf

# tf.constant: 말 그대로 상수입니다.
hello = tf.constant('Hello, TensorFlow!')
print(hello)

# 그래프 생성
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)  # a + b 로도 쓸 수 있음
print(c)

# 위에서 변수와 수식들을 정의했지만, 실행이 정의한 시점에서 실행되는 것은 아닙니다.
# 다음처럼 Session 객제와 run 메소드를 사용할 때 계산이 됩니다.
# 따라서 모델을 구성하는 것과, 실행하는 것을 분리하여 프로그램을 깔끔하게 작성할 수 있습니다.
# 그래프를 실행할 세션을 구성합니다.
sess = tf.Session()
# sess.run: 설정한 텐서 그래프(변수나 수식 등등)를 실행합니다.
print(sess.run(hello))
print(sess.run([a, b, c]))

# 세션을 닫습니다.
sess.close()
```



## 플레이스홀더와 변수

텐서플로로 프로그래밍할 때 알아야 할 가장 중요한 개념 두 개가 있다면 바로 플레이스홀더와 변수입니다.

**플레이스홀더**는 그래프에 사용할 입력값을 나중에 받기 위해 사용하는 매개변수라고 생각하면 됩니다.  
그리고 **변수**는 그래프를 최적화하는 용도로 텐서플로가 학습한 결과를 갱신하기 위해 사용하는 변수입니다.  
이 변수의 값들이 바로 신경망의 성능을 좌우하게 됩니다.

아마 잘 이해되지 않는 분도 계실 텐데, 저 역시 처음 텐서플로를 접했을 때 가장 혼란스러웠던 개념입니다.  
알고보면 쉬운 개념이라 코드를 계속 따라가다 보면 곧 이해하실 수 있을 겁니다.

먼저 플레이스 홀더는 다음과 같이 사용합니다

In [62]:
# None은 크기가 정해지지 않았음을 의미합니다
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_4:0", shape=(?, 3), dtype=float32)


위 코드를 실행하면 다음과 같이 Placeholder라는 (?,3) 모양의 float32 자료형을 가진 텐서가 생성된 것을 확인할 수 있습니다


```shell
Tensor("Placeholder:0", shape=(?, 3), dtype=float32)
```

나중에 플레이스홀더 X에 넣을 자료를 다음과 같이 정의해볼 수 있습니다.  
앞서 텐서 모양을 (?,3)으로 정의했으므로, 두 번째 차원은 요소를 3개씩 가지고 있어야 합니다


In [0]:
x_data = [[1,2,3],[4,5,6]]

다음은 변수들을 정의해보겠습니다

In [0]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

각각 W와 b에 텐서플로의 변수를 생성하여 할당합니다.  
W는 [3,2] 행렬 형태의 텐서, b는 [2,1] 행렬 형태의 텐서로,   
tf.random_normal 함수를 이용해 **정규분포**의 무작위 값으로 초기화합니다.  
물론 다른 생성 함수를 사용하거나, 다음처럼 직접 원하는 텐서의 형태의 데이터를 만들어서 넣어줄 수도 있습니다.

```python
W = tf.variable([[0.1,0.1],[0.2,0.2],[0.3,0.3]])
```
다음으로 입력값과 변수들을 계산할 수식을 작성해보겠습니다.  
X와 W가 행렬이기 때문에 tf.matmul 함수를 사용하여야 합니다.  
행렬이 아닌 경우에는 단순히 곱셈 연산자(*)나 tf.mul 함수를 사용하면 됩니다.
  


In [0]:
expr = tf.matmul(X,W) + b

텐서플로우로 딥러닝을 하기 위해서 반드시 수학을 잘 알아야 하는 것은 아닙니다.  
하지만 꼭 하나 알고 있어야 하는 것이 있다면 행렬인데, 특히 그중 딱 하나!  
행렬곱 정의는 알고 있는 것이 좋습니다 

[행렬곱 정의](https://ko.wikipedia.org/wiki/%ED%96%89%EB%A0%AC_%EA%B3%B1%EC%85%88)

행렬곱 정의에 따라, 앞서 X에 넣을 데이터를 [2,3] 형태의 행렬로 정의하였으므로,   
행렬곱을 하기 위해서 W의 형태를 [3,2]로 정의한 것입니다.  
참고로 [2,3] 행렬이라며 2가 행의 개수, 3이 열의 개수입니다.

이제 연산을 실행하고 결과를 출력하여, 설정한 텐서들과 계산된 그래프의 결과를 확인해보겠습니다

In [66]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.8638351  -0.8311099 ]
 [ 0.6512873   0.9720324 ]
 [ 0.35349658  1.4516944 ]]
=== b ===
[[-1.0245268]
 [-0.1978673]]
=== expr ===
[[ 0.47470248  4.443511  ]
 [ 1.7242085  10.048021  ]]


**tf.global_variables_initializer**는 앞에 정의한 변수들을 초기화하는 함수입니다.  
기존의 학습한 값들을 가져와 사용하는 것이 아닌 처음 실행하는 것이라면,  
연산을 실행하기 전엔 반드시 이 함수를 이용해 변수들을 초기화해야 합니다.  

**feed_dict** 매개변수는 그래프를 실행할 때 사용할 입력값을 지정합니다.  

**expr** 수식에는 X,W,b를 사용했는데, 이중 X가 플레이스홀더라 X에 값을 넣어주지 않으면  
계산에 사용할 값이 없으므로 에러가 납니다.  
따라서 미리 정의해둔 x_data를 X의 값으로 넣어주었습니다

```shell
=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 1.1002327   0.43592995]
 [ 1.3414483  -0.7337341 ]
 [-0.09329127  1.0130547 ]]
=== b ===
[[-0.6259896]
 [ 0.9517739]]
=== expr ===
[[ 2.8772657  1.3816364]
 [11.500198   5.105151 ]]
```
실행한 결과를 보면 X(즉 x_data)는 [2,3], W는 [3,2] 형태이고,   
결과값은 행과 열의 수가 각각 X의 행의 개수와 W의 열의 개수인 [2,2] 형태임을 확인할 수 있습니다.  
구체적인 수치는 문서와 다를텐데, 앞서 변수 W와 b를 무작위 앖으로 초기화 했기 때문입니다.

아래는 전체 코드입니다


```python
# 플레이스홀더와 변수의 개념을 익혀봅니다
import tensorflow as tf

# tf.placeholder: 계산을 실행할 때 입력값을 받는 변수로 사용합니다.
# None 은 크기가 정해지지 않았음을 의미합니다.
# 빈 통?을 만들어봅니다
X = tf.placeholder(tf.float32, [None, 3])
print(X)

# X 플레이스홀더에 넣을 값 입니다.
# 플레이스홀더에서 설정한 것 처럼, 두번째 차원의 요소의 갯수는 3개 입니다.
x_data = [[1, 2, 3], [4, 5, 6]]

# tf.Variable: 그래프를 계산하면서 최적화 할 변수들입니다. 이 값이 바로 신경망을 좌우하는 값들입니다.
# tf.random_normal: 각 변수들의 초기값을 정규분포 랜덤 값으로 초기화합니다.
# Y = W(가중치) * X + b(편향)
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

# 입력값과 변수들을 계산할 수식을 작성합니다.
# tf.matmul 처럼 mat* 로 되어 있는 함수로 행렬 계산을 수행합니다.
expr = tf.matmul(X, W) + b

sess = tf.Session()
# 위에서 설정한 Variable 들의 값들을 초기화 하기 위해
# 처음에 tf.global_variables_initializer 를 한 번 실행해야 합니다.
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
# expr 수식에는 X 라는 입력값이 필요합니다.
# 따라서 expr 실행시에는 이 변수에 대한 실제 입력값을 다음처럼 넣어줘야합니다.
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()
```



## 선형 회귀 모델 구현하기

**선형 회귀**란 간단하게 말해, 주어진 x와 y값을 가지고 서로 간의 관계를 파악하는 것입니다.  
이 관계를 알고 나면 새로운 x 값이 주어졌을 때 y 값을 쉽게 알 수 있습니다.  
어떤 입력에 대한 출력을 예측하는 것, 이것이 바로 머신러닝의 기본입니다.

이제 텐서플로의 최적화 함수를 이용해 X와 Y의 상관관계를 분석하는   
기초적인 선형 회귀 모델을 만들고 실행해보겠습니다.  
여기서는 다음과 같이 주어진 x_data와 y_data의 상관관계를 파악해보고자 합니다.

In [0]:
x_data = [1,2,3]
y_data = [1,2,3]

먼저 x와 y의 상관관계를 설명하기 위한 변수들인 W와 b를   
각각 -1.0부터 1.0 사이의 **균등분포**를 가진 무작위 값으로 초기화합니다.

In [0]:
W = tf.Variable(tf.random_uniform([1],-1.0,1.0))
b = tf.Variable(tf.random_uniform([1],-1.0,1.0))

다음은 자료를 입력받을 플레이스 홀더를 설정합니다

In [0]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

그 다음으로 X와 Y의 상관관계(여기선 선형관계)를 분석하기 위한 수식을 작성합니다

In [0]:
hypothesis = W * X + b

**이 수식은 W와의 곱과 b와의 합을 통해 X와 Y의 관계를 설명하겠다는 뜻입니다.**  
다시 말해 X가 주어졌을 때 Y를 만들어 낼 수 있는 W와 b를 찾아내겠다는 의미이기도 합니다.  
W는 **가중치(weight)**, b는 **편향(bias)** 이라고 하며,  
이 수식은 선형 회귀는 물론 신경망 학습에 가장 기본이 되는 수식입니다.  
여기서는 W와 X가 행렬이 아니므로 tf.matmul이 아니라 기본 곱셈 연산자를 사용했습니다.

다음으로 손실 함수를 작성해보겠습니다.  
**손실 함수**는 한 쌍(x,y)의 데이터에 **손실값**을 계산하는 함수입니다.  
손실값이란 실제값과 모델로 예측한 값이 얼마나 차이가 나는가를 나타내는 값입니다.  
즉, 손실값이 작을수록 그 모델이 X와 Y의 관계를 잘 설명하고 있다는 뜻이고,  
주어진 X값에 대한 Y값을 정확하게 예측할 수 있다는 뜻입니다.  
그리고 이 손실을 전체 데이터에 대해 구한 경우 이를 **비용**이라고 합니다.  

#### 즉, 학습이란 변수들의 값을 다양하게 넣어 계산해보면서 
#### 이 손실을 최소화하는 W와 b의 값을 구하는 것입니다.

손실값으로는 **예측값과 실제값의 거리**를 가장 많이 사용하며, 우리도 이를 사용합니다.  
따라서 손실값은 예측값에서 실제값을 뺀 뒤 제곱하여,  
그리고 비용은 모든 데이터에 대한 손실값의 평균을 내어 구합니다

In [0]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

텐서플로우는 이러한 수식 계산을 위한 다양한 함수를 구현해 제공합니다  
[다양한 함수 공부하기](https://www.tensorflow.org/api_docs/)

마지막으로 텐서플로우가 기본 제공하는 **경사하강법(gradient descent)** 최적화 함수를 이용해   
손실값을 최소화하는 연산 그래프를 생성합니다.  

In [0]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

**최적화 함수**란 가중치와 편향 값을 변경해가면서 손실값을 최소화하는  
가장 최적화된 가중치와 편향 값을 찾아주는 함수입니다.  
이때 값들은 무작위로 변경하면 시간이 너무 오래 걸리고 학습 시간도 에측하기 어려울 것입니다.  
따라서 빠르게 최적화하기 위한, 즉 빠르게 학습하기 위한 다양한 방법을 사용합니다.  

경사하강법은 그러한 최적화 방법 중 가장 기본적인 알고리즘으로,   
다음 그래프와 같이 함수의 기울기를 구하고 기울기가 낮은 쪽으로 계속 이동시키면서  
최적의 값을 찾아 나가는 방법입니다.  

최적화 함수의 매개변수인 learning_rate, 즉 **학습률**은 학습을 얼마나 '급하게' 할 것인가를 설정하는 값입니다.  
값이 너무 크면 최적의 손실값을 찾지 못하고 지나치게 되고, 값이 너무 적으면 학습 속도가 매우 느려집니다.  
이렇게 학습을 진행하는 과정에 영향을 주는 변수를 **하이퍼파라미터**라 하며,  
이 값에 따라 학습 속도나 신경망 성능이 크게 달라질 수 있습니다.  
머신러닝에서는 이 하이퍼파리미터를 잘 튜닝하는 것이 큰 과제이기도 합니다.  


이제 선형 회귀 모델을 다 만들었으니, 그래프를 실행해 학습을 시키고 결과를 확인해보겠습니다

먼저 앞 절에서와 같이 세션을 생셩하고 변수들을 초기화합니다.  
한가지, 이번에는 파이썬의 with 기능을 이용해 세션 블록을 만들고 세션 종료를 자동으로 처리하도록 만들어봤습니다



In [0]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

다음은 최적화를 수행하는 그래프인 train_op를 실행하고,   
실행 시마다 변화하는 손실값을 출력하는 코드입니다.  

학습을 100번 수행하며, feed_dict 매개변수를 통해,  
상관관계를 알아내고자 하는 데이터인 x_data와 y_data를 입력해줍니다.

In [74]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(100):
    _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, 
                                                        Y: y_data})

    print(step, cost_val, sess.run(W), sess.run(b))

(0, 14.477139, array([0.75695276], dtype=float32), array([0.9890936], dtype=float32))
(1, 0.29238936, array([0.58815944], dtype=float32), array([0.8884938], dtype=float32))
(2, 0.11727575, array([0.61714643], dtype=float32), array([0.87553126], dtype=float32))
(3, 0.10977927, array([0.62426394], dtype=float32), array([0.8535664], dtype=float32))
(4, 0.10454166, array([0.6335244], dtype=float32), array([0.8331475], dtype=float32))
(5, 0.09957555, array([0.6423093], dtype=float32), array([0.81310827], dtype=float32))
(6, 0.09484563, array([0.6509106], dtype=float32), array([0.7935629], dtype=float32))
(7, 0.0903404, array([0.65930223], dtype=float32), array([0.77448606], dtype=float32))
(8, 0.08604916, array([0.6674924], dtype=float32), array([0.75586796], dtype=float32))
(9, 0.08196176, array([0.6754857], dtype=float32), array([0.7376974], dtype=float32))
(10, 0.07806852, array([0.6832867], dtype=float32), array([0.71996367], dtype=float32))
(11, 0.07436019, array([0.69090027], dtype=fl

이 학습의 진행 상황을 출력해보면 다음과 같이 손실값과 변수들의 변화를 확인할 수 있습니다.  
다음과 같이 손실값이 점점 줄어든다면 학습이 정상적으로 이뤄지고 있는 것입니다.

```shell
(0, 18.750364, array([1.2408829], dtype=float32), array([-0.04855856], dtype=float32))
(1, 0.22635157, array([1.0354823], dtype=float32), array([-0.13520001], dtype=float32))
(2, 0.0049655237, array([1.0564455], dtype=float32), array([-0.12235291], dtype=float32))
(3, 0.0022135882, array([1.0527042], dtype=float32), array([-0.12046052], dtype=float32))
(4, 0.0020783849, array([1.0516979], dtype=float32), array([-0.1174501], dtype=float32))
(5, 0.001979311, array([1.0504265], dtype=float32), array([-0.11463923], dtype=float32))
(6, 0.0018852801, array([1.0492175], dtype=float32), array([-0.11188197], dtype=float32))
(7, 0.0017957288, array([1.048034], dtype=float32), array([-0.10919257], dtype=float32))
(8, 0.0017104292, array([1.0468793], dtype=float32), array([-0.10656763], dtype=float32))
(9, 0.0016291835, array([1.0457523], dtype=float32), array([-0.10400582], dtype=float32))
(10, 0.0015517954, array([1.0446525], dtype=float32), array([-0.10150557], dtype=float32))
... (이하 생략)
```
이제 두근거리는 마음으로 학습에 사용되지 않았던 값인 5와 2.5를 X값으로 넣고 결과를 확인해봅니다


In [75]:
print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

RuntimeError: ignored

저는 결과가 다음처럼 나왔습니다.


```shell
'X: 5, Y:4.9358253'
'X: 2.5, Y:2.4946632'
```
### 기대한 대로 X가 5일 때는 Y값으로 5 근처를, 2.5일 때는 2.5 근처를 정확히 예측해내었습니다.  
### 텐서플로와 머신러닝의 세계로 오신 것을 환영합니다!

아래는 전체 코드입니다

```python
# X 와 Y 의 상관관계를 분석하는 기초적인 선형 회귀 모델을 만들고 실행해봅니다.
import tensorflow as tf

# 학습 데이터
x_data = [1, 2, 3]
y_data = [1, 2, 3]

# 가중치, 편향 초깃값 설정
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

# name: 나중에 텐서보드등으로 값의 변화를 추적하거나 살펴보기 쉽게 하기 위해 이름을 붙여줍니다.
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")
print(X)
print(Y)

# X 와 Y 의 상관 관계를 분석하기 위한 가설 수식을 작성합니다.
# y = W * x + b
# W 와 X 가 행렬이 아니므로 tf.matmul 이 아니라 기본 곱셈 기호를 사용했습니다.
hypothesis = W * X + b

# 손실 함수를 작성합니다.
# mean(h - Y)^2 : 예측값과 실제값의 거리를 비용(손실) 함수로 정합니다.
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# 텐서플로우에 기본적으로 포함되어 있는 함수를 이용해 경사 하강법 최적화를 수행합니다.
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
# 비용을 최소화 하는 것이 최종 목표
train_op = optimizer.minimize(cost)

# 세션을 생성하고 초기화합니다.
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # 최적화를 100번 수행합니다.
    for step in range(100):
        # sess.run 을 통해 train_op 와 cost 그래프를 계산합니다.
        # 이 때, 가설 수식에 넣어야 할 실제값을 feed_dict 을 통해 전달합니다.
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})

        print(step, cost_val, sess.run(W), sess.run(b))

    # 최적화가 완료된 모델에 테스트 값을 넣고 결과가 잘 나오는지 확인해봅니다.
    print("\n=== Test ===")
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))
```

